# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean -DskipTests -P azure install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.RC_PERSON_TOKEN }}

      - name: Lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
         context: .
         push: true
         tags: |
           ghcr.io/${{ env.REPO }}:${{ github.sha }}
           ghcr.io/${{ env.REPO }}:latest
         cache-from: type=gha
         cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write
      
    steps:
      # 重新设置 REPO 环境变量（因为 job 间不共享环境）
      - name: Lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      # 登录 Azure
      - name: Azure Login via CLI
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            -t ${{ secrets.AZURE_TENANT_ID }}
          az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 部署到 Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: emsp-accts-2
          # 重要：使用服务主体而非发布配置文件
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
          slot-name: production